[theme]
base="dark"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false
runOnSave = false          # disable auto-run on file save
fileWatcherType = "none"   # disable file watching / auto-restarts

[browser]
gatherUsageStats = false